
import __ASTRO_IMAGE_IMPORT_Zw5YFO from "./images/blog-wishpond-com.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fblog-wishpond.md";
import __ASTRO_IMAGE_IMPORT_3mXVv from "./images/emojiq.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Femojiq.md";
import __ASTRO_IMAGE_IMPORT_Z2udlPY from "./images/mateus.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpost-1.md";
import __ASTRO_IMAGE_IMPORT_Z14MVi1 from "./images/mateus.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpost-10.md";
import __ASTRO_IMAGE_IMPORT_Z14MNhD from "./images/mateus.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpost-11.md";
import __ASTRO_IMAGE_IMPORT_Z2uddPB from "./images/mateus.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpost-2.md";
import __ASTRO_IMAGE_IMPORT_Z2ud5Pe from "./images/mateus.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpost-3.md";
import __ASTRO_IMAGE_IMPORT_Z2ucWOQ from "./images/mateus.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpost-4.md";
import __ASTRO_IMAGE_IMPORT_Z2ucOOt from "./images/mateus.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpost-5.md";
import __ASTRO_IMAGE_IMPORT_Z2ucGO6 from "./images/mateus.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpost-6.md";
import __ASTRO_IMAGE_IMPORT_Z2ucyNI from "./images/mateus.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpost-7.md";
import __ASTRO_IMAGE_IMPORT_Z2ucqNl from "./images/mateus.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpost-8.md";
import __ASTRO_IMAGE_IMPORT_Z2uciMX from "./images/mateus.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpost-9.md";
import __ASTRO_IMAGE_IMPORT_Z1rQsym from "./images/mattttca.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fmatttt.md";
import __ASTRO_IMAGE_IMPORT_utSfR from "./images/placeholder.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpost-12.md";
import __ASTRO_IMAGE_IMPORT_Z1zhItY from "./images/salonlanci.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fsalonlanci.md";
import __ASTRO_IMAGE_IMPORT_hAqvM from "./images/wishpond-com.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fwishpond.md";
export default new Map([["./images/blog-wishpond-com.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fblog-wishpond.md", __ASTRO_IMAGE_IMPORT_Zw5YFO], ["./images/emojiq.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Femojiq.md", __ASTRO_IMAGE_IMPORT_3mXVv], ["./images/mateus.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpost-1.md", __ASTRO_IMAGE_IMPORT_Z2udlPY], ["./images/mateus.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpost-10.md", __ASTRO_IMAGE_IMPORT_Z14MVi1], ["./images/mateus.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpost-11.md", __ASTRO_IMAGE_IMPORT_Z14MNhD], ["./images/mateus.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpost-2.md", __ASTRO_IMAGE_IMPORT_Z2uddPB], ["./images/mateus.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpost-3.md", __ASTRO_IMAGE_IMPORT_Z2ud5Pe], ["./images/mateus.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpost-4.md", __ASTRO_IMAGE_IMPORT_Z2ucWOQ], ["./images/mateus.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpost-5.md", __ASTRO_IMAGE_IMPORT_Z2ucOOt], ["./images/mateus.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpost-6.md", __ASTRO_IMAGE_IMPORT_Z2ucGO6], ["./images/mateus.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpost-7.md", __ASTRO_IMAGE_IMPORT_Z2ucyNI], ["./images/mateus.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpost-8.md", __ASTRO_IMAGE_IMPORT_Z2ucqNl], ["./images/mateus.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpost-9.md", __ASTRO_IMAGE_IMPORT_Z2uciMX], ["./images/mattttca.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fmatttt.md", __ASTRO_IMAGE_IMPORT_Z1rQsym], ["./images/placeholder.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpost-12.md", __ASTRO_IMAGE_IMPORT_utSfR], ["./images/salonlanci.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fsalonlanci.md", __ASTRO_IMAGE_IMPORT_Z1zhItY], ["./images/wishpond-com.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fwishpond.md", __ASTRO_IMAGE_IMPORT_hAqvM]]);
		